// Products
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const PRODUCT_PROFILE_SUCCESS = 'PRODUCT_PROFILE_SUCCESS';
export const PRODUCT_ADD_TO_CART_SUCCESS = 'PRODUCT_ADD_TO_CART_SUCCESS';

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';
